### ISSUE TITLE
Error in running the worked example

### ISSUE THREAD

**Issue by NavidHaghdadi** [UNSW-CEEM/NEMOSIS#1]
Hi Nick, someone here is getting error when running the worked example:

![image](https://user-images.githubusercontent.com/24327931/59580408-5ef50480-9114-11e9-963a-0e29aa646a53.png)

![image](https://user-images.githubusercontent.com/24327931/59580367-366d0a80-9114-11e9-9cf8-a53958e64bfc.png)

**Comment by nick-gorman** [comment]
Apologies for the late reply. I believe this is due to AEMO changing a data url on their website, this issue should be fixed in the latest release.
