### ISSUE TITLE
table `TRADINGPRICE` does not have an `INTERVENTION` column

### ISSUE THREAD

**Issue by jotaigna** [UNSW-CEEM/NEMOSIS#13]
When retrieving data for `TRADINGPRICE` no data will return for the `INTERVENTION` column and thus the cached csv file will be saved without it.

However, a subsequent retrieval from feather causes the following error:
`ArrowInvalid: Field named INTERVENTION is not found`
because the schema as defined in defaults.py includes this column.

See PR #12 for a fix. I have tested locally and there are no other column inconsistencies for that table that I can see.

**Comment by nick-gorman** [comment]
Hi @jotaigna , 

Thanks for the issue and the PR. Hopefully I get around to including the fix in a new release soon.

Cheers,
Nick

**Comment by eddie-atkinson** [comment]
For anyone who's bumping into this one and can't wait for a release, there is a `select_columns` option for the `dynamic_data_compiler` function in `data_fetch_methods`. Using this you can achieve the same effect as the PR above by passing it all the columns except for `INTERVENTION`.

For example:

```
from nemosis import data_fetch_methods
...
desired_columns = ['SETTLEMENTDATE', 'REGIONID', 'RRP', 'RAISE6SECRRP', 'RAISE60SECRRP',
                     'RAISE5MINRRP',  'LOWER6SECRRP', 'LOWER60SECRRP', 'LOWER5MINRRP']
df_w = data_fetch_methods.dynamic_data_compiler(start_time, end_time, table, data_cache, select_columns=desired_columns)
...
```

**Comment by nick-gorman** [comment]
Thanks @jotaigna and @eddie-atkinson. This should be fixed in the latest version.
