### ISSUE TITLE
Enhance logging + user feedback

### ISSUE THREAD

**Issue by prakaa** [UNSW-CEEM/NEMOSIS#17]
- Move print user feedback to logging module
  - severity of logging - e.g. warning, error
  - can be extended to debugging for development
- More precise error logging 
  -  currently limited by which variables are available within each private function
- More logging for other user input issues (e.g. invalid table names)

**Comment by nick-gorman** [comment]
The v3.0.0 release includes errors for various invalid inputs from users. Let me know if you think other warning or error logging/raising needs to be added.
