### ISSUE TITLE
Causer Pays Elements fetching needs to be fixed

### ISSUE THREAD

**Issue by prakaa** [UNSW-CEEM/NEMOSIS#19]
Causer Pays elements mapping file was previously a static url link to a table updated on ad-hoc basis.

Now, "versioned" through [NEMWeb](http://www.nemweb.com.au/Reports/Current/Causer_Pays_Elements/).

 Need to implement fetching similar to DUDETAILSUMMARY (`search_type = end`) to fetch the latest .csv when user requests it.

**Comment by nick-gorman** [comment]
This has been implemented.
