### ISSUE TITLE
NEMOSIS dynamic_data_compiler

### ISSUE THREAD

**Issue by fnbillimor** [UNSW-CEEM/NEMOSIS#27]
Hi 

I as using NEMOSIS in conjunction with NEMSEER.  When I pull data from the dynamic data compiler under a parquet format, it seems like all the data is saved as a datetime file.  

```
    nemosis_data = nemosis.dynamic_data_compiler(
        nemosis_start,
        time,
        "TRADINGPRICE",
        nemosis_cache,
        filter_cols=["REGIONID"],
        filter_values=(["SA1"],),
        fformat="parquet",
    )
    
    actual_price = nemosis_data.groupby("SETTLEMENTDATE")["RRP"].sum()[time]
```

As a result it is unable to undertake the sum( ) operation as that is only restricted to float/int objects.  This seems to be a recent issue, as I have run the same function a few days ago and did not have any issues.  A printout of the "nemosis_data" variable is set out below.  
```

INFO: Query raw data already downloaded to nemseer_cache
INFO: Converting PRICE data to xarray.
Compiling data for table TRADINGPRICE.
Returning TRADINGPRICE.
          SETTLEMENTDATE REGIONID                           RRP  \
2729 2021-01-01 00:30:00      SA1 1970-01-01 00:00:00.000000035   

                      RAISE6SECRRP                 RAISE60SECRRP RAISE5MINRRP  \
2729 1970-01-01 00:00:00.000000001 1970-01-01 00:00:00.000000001   1970-01-01   

                       RAISEREGRRP                  LOWER6SECRRP  \
2729 1970-01-01 00:00:00.000000010 1970-01-01 00:00:00.000000001   

                     LOWER60SECRRP LOWER5MINRRP                   LOWERREGRRP  \
2729 1970-01-01 00:00:00.000000003   1970-01-01 1970-01-01 00:00:00.000000012   

     PRICE_STATUS  
2729         FIRM  
```

**Comment by nick-gorman** [comment]
Hi @fnbillimor,

Thanks for reporting this issue, we really appreciate user feedback.

However, I'm having trouble replicating your error. Could you provide the complete details of the example, i.e. including the start and end time you are using?

**Comment by fnbillimor** [comment]
Hi Nick - Thank you for getting back to me.  I have uploaded the full code I have used to the github address below.  I am using a start and end time based on the calender year 2021.

https://github.com/fnbillimor/PD_prices

**Comment by nick-gorman** [comment]
@fnbillimor can you please try and run the code below on your machine and let me know if it works or not? It should just be a simplified version of what you are doing, it appears to be working fine for me.

```python
import nemosis

analysis_start = "2021/01/01 00:30:00"
analysis_end = "2022/01/01 00:00:00"
nemosis_cache = 'nemosis_cache/'

nemosis.cache_compiler(analysis_start,
                       analysis_end,
                       "TRADINGPRICE",
                       'nemosis_cache',
                       fformat="parquet"
                       )

nemosis_data = nemosis.dynamic_data_compiler(
    analysis_start,
    analysis_end,
    "TRADINGPRICE",
    nemosis_cache,
    filter_cols=["REGIONID"],
    filter_values=(["SA1"],),
    fformat="parquet",
)

time = str(analysis_end).replace("-", "/")

print(nemosis_data['RRP'].sum())
# 1791056.4400000002

print(nemosis_data.groupby("SETTLEMENTDATE")["RRP"].sum()[time])
# 139.28

print(nemosis_data.dtypes)
# SETTLEMENTDATE    datetime64[ns]
# REGIONID                  object
# RRP                      float64
# RAISE6SECRRP             float64
# RAISE60SECRRP            float64
# RAISE5MINRRP             float64
# RAISEREGRRP              float64
# LOWER6SECRRP             float64
# LOWER60SECRRP            float64
# LOWER5MINRRP             float64
# LOWERREGRRP              float64
# PRICE_STATUS              object
# dtype: object
```

**Comment by prakaa** [comment]
Hi @fnbillimor ,

I don't seem to have the issue either. This worked for me:
```python
time = "2021/01/01 12:00:00"
# get actual demand data for forecasted_time
# nemosis start time must precede end of interval of interest by 5 minutes
nemosis_start = (
    datetime.strptime(time, "%Y/%m/%d %H:%M:%S") - timedelta(minutes=30)
).strftime("%Y/%m/%d %H:%M:%S")
# compile data using nemosis, using cached parquet and filtering out interventions
# select appropriate region
nemosis_data = nemosis.dynamic_data_compiler(
    nemosis_start,
    time,
    "TRADINGPRICE",
    nemosis_cache,
    filter_cols=["REGIONID", "PRICE_STATUS"],
    filter_values=(["SA1"], ["FIRM"]),
    fformat="parquet",
)
nemosis_data["RRP"].values[0]
```
![image](https://user-images.githubusercontent.com/29934785/196890680-57bd2572-1155-47ba-bb8f-2b6f58dcb8c6.png)

On another note, I noticed that you are using code from the `nemseer` example. As you may have seen, I wrote those with a note at the start - the code I used in those examples was simple, but by no means efficient.

This is good timing as I am working on updating examples in `nemseer` (I have added pre-dispatch demand forecast error for 2021) and am currently working on price convergence with PD + P5MIN (as you are). I will probably have some code in the next day or two and can share when I'm done - I'll see if I can write an example function that is a bit more efficient than the ones I wrote for demand.

**Comment by prakaa** [comment]
@fnbillimor I have updated the PD demand forecast error example. 

You can adapt this for price. The code you'll probably be interested in is the pure-pandas vectorised function - should be faster: https://nemseer.readthedocs.io/en/latest/examples/pd_demand_forecast_error_2021.html#pure-pandas-implementation-vectorised-code

Once I get around to finishing the price convergence example (working on that now), I will let you know

**Comment by prakaa** [comment]
@fnbillimor still a WIP, but code under "Looking at price convergence more systematically" might be helpful, though noting that I have combined PD and P5MIN forecasts and dropped the overlapping PD forecasts: https://github.com/UNSW-CEEM/NEMSEER/blob/fff6a482ae3f6cd63e8ed03accdfe2fc2e268986/docs/source/examples/price_convergence_2021.ipynb

**Comment by fnbillimor** [comment]
Thank you @prakaa and @nick-gorman  - this is super helpful.  I will try this code.

**Comment by prakaa** [comment]
@fnbillimor the example is now complete and waiting in a PR. See the link below. You should be able to use this code directly, but you'll need to swap out the 5 minute pricing for trading price: https://nemseer--45.org.readthedocs.build/en/45/examples/price_convergence_2021.html
