### ISSUE TITLE
Pandas issue for read-only workbook

### ISSUE THREAD

**Issue by RPBatchelor** [UNSW-CEEM/NEMOSIS#31]
I tried running the example code for generator bidding data (https://github.com/UNSW-CEEM/NEMOSIS/blob/master/examples/generator_bidding_data.ipynb)

On running cell 4 (downloading the static table) I get a large error which I beleive traces back to pandas use of pyxl and handling of read only workbooks (which I assume the generator and load static table is). 
![image](https://user-images.githubusercontent.com/65215243/220301297-5fe1c6e1-dfae-416c-addd-3a30582f7572.png)

If I change line 569 in pandas _openpyxl.py file (vevn/lib/pandas/io/excel/_openpyxl.py) to be read_only=False, the error disappears and I can downlaod the data

![image](https://user-images.githubusercontent.com/65215243/220302017-90a042b0-e502-47ca-8378-123f1afbd38c.png)

I assume Nemosis should pass command to change default for this setting within pandas?

**Comment by nick-gorman** [comment]
@RPBatchelor, apologies for not looking at this earlier.

Which versions of pandas, and openpyxl are you having this issue with? 

I haven't been able to replicate on my end.
