### ISSUE TITLE
Can't download PREDISPATCHPRICE and P5MIN_REGIONSOLUTION

### ISSUE THREAD

**Issue by notuntoward** [UNSW-CEEM/NEMOSIS#32]
I'm unable to download data from either of these tables: PREDISPATCHPRICE or P5MIN_REGIONSOLUTION

For example, this code

> from nemosis import defaults
> print(defaults.table_columns['PREDISPATCHPRICE'])

gives me a key error.  It seems like these both should be dynamic tables, like, for example, DISPATCHPRICE.

But is that not the case?

**Comment by nick-gorman** [comment]
Hi @notuntoward 

Unfortunately, NEMOSIS isn't configured with all the MMS data tables, as each table requires some manual config to set up we've just added a subset of tables focusing on the most important ones.

However, the tables related to forecast data, such as PREDISPATCHPRICE or P5MIN_REGIONSOLUTION, should be accessible using a similar tool called NEMSEER: https://github.com/UNSW-CEEM/NEMSEER

**Comment by notuntoward** [comment]
Thanks!
