### ISSUE TITLE
Add ROOFTOP_PV_ACTUAL table, or all tables?

### ISSUE THREAD

**Issue by mdavis-xyz** [UNSW-CEEM/NEMOSIS#33]
Hi,

This looks like a great library. How can I use it to download `ROOFTOP_PV_ACTUAL`? It seems like only some tables are supported. But the table schemas don't appear to be hard-coded within this library. What does it take to add another table, as a developer?

## Option 1: Please just add `ROOFTOP_PV_ACTUAL`

Or tell me which files to modify, and I'll write a PR. Then as a user I can load it.

## Option 2: add a way for end-users to load obscure tables

Maybe a function where the user says what the table name is, whether it's static, which columns to deduplicate by, etc.

## Option 3: add _all_ tables to the library

This would certainly be best for the user experience. Although it is hard to do.

I have previously web-scraped the schemas from the data model report. So I could give you a big json of all the column types. (And the script that produced them.) That might help.

Some tricky things to note for this approach:

* there is actually a table that's in the dataset, but not the documentation. (A CO2 one)
* there are two columns for plant capacity that are documented as whole numbers, but are in fact decimals
* the market notices sometimes contain newline files, which breaks some CSV parsing

**Comment by nick-gorman** [comment]
@mdavis-xyz thanks for raising the issue, definitely looks like a table worth adding.

Addressing your various points:

- To add new monthly archive table to NEMOSIS you need to edit the following config files: defaults.py, processing_info_maps.py, data_fetch_methods.py (just the dict at the end of the file). It's a messy process but relatively straightforward once you get the hang of it.
- I'll try and do option 1 in the next couple of days, shouldn't take long.
- Options 2 and 3 are both big changes, and I'd probably re-factor NEMOSIS pretty heavily if I went down this path.
- For accessing tables that aren't included in NEMOSIS I'd also recommend @prakaa excellent tool (https://github.com/prakaa/mms-monthly-cli) which is simpler than NEMOSIS but can get the job done just fine if you're python savy

**Comment by nick-gorman** [comment]
Addressed in release 3.6.0: https://github.com/UNSW-CEEM/NEMOSIS/releases/tag/v3.6.0
