### ISSUE TITLE
August 2024 download issue

### ISSUE THREAD

**Issue by Starstrike99** [UNSW-CEEM/NEMOSIS#40]
The latest version of NEMOSIS is not downloading monthly data tables from August 2024.

This may be related to a change of naming convention from AEMO - for example in July, Scada data was labelled:
PUBLIC_DVD_DISPATCH_UNIT_SCADA_202407010000.zip
whereas in the August data set, it is labelled:
PUBLIC_ARCHIVE#DISPATCH_UNIT_SCADA#FILE01#202408010000.zip

**Comment by nick-gorman** [comment]
Thanks for bringing to our attention @Starstrike99 

It's on the to-do list, but it's a pretty big change, so it may take a few weeks to fix nemosis properly.

A short-term fix, might be to manually download the August file to the local cache, and rename the file to the old style of name. Then querying the data with nemosis should work, as it will read from the cache before looking online.

**Comment by Starstrike99** [comment]
Thank you and great advice. I've successfully downloaded what I need for now via the cache.

**Comment by nick-gorman** [comment]
Release v3.8.0 has the new functionality, the windows EXE hasn't be updated but the python API has. Let me know if you have any issues.
