### ISSUE TITLE
Additional of DIRECTION column

### ISSUE THREAD

**Issue by Starstrike99** [UNSW-CEEM/NEMOSIS#41]
The latest dataset includes a column "DIRECTION" in BIDDAYOFFER_D and BIDPEROFFER_D, to support bidirectional units.

Could this column be added to NEMOSIS?

**Comment by nick-gorman** [comment]
Yep, on the todo list, should get done in the next couple of weeks.

**Comment by nick-gorman** [comment]
Release v3.8.0 has added this column, the windows EXE hasn't be updated but the python API has. Let me know if you have any issues.

**Comment by Starstrike99** [comment]
Thank you!
